#!/usr/bin/env bash

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
#set -Eeuxo pipefail
set -Eeuo pipefail

BASE_PATH=$(dirname $0); cd $BASE_PATH

SOLC_VERSION=$1
SOLC_EXACT_VERSION=$(curl -s https://binaries.soliditylang.org/macosx-amd64/list.txt | grep $SOLC_VERSION)
if [ -x $SOLC_EXACT_VERSION ]; then
  echo "Already downloaded $SOLC_EXACT_VERSION"
else
  curl -OL "https://binaries.soliditylang.org/macosx-amd64/$SOLC_EXACT_VERSION"
  chmod +x $SOLC_EXACT_VERSION
fi

rm -f solc
ln -s $SOLC_EXACT_VERSION solc

echo "solc version changed to $SOLC_EXACT_VERSION"
